version: '3'
services:
  pybossa:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
      args:
       - PYBOSSA_COMMIT="${PYBOSSA_COMMIT:-master}"
    environment:
      - PYBOSSA_SECRET=test-only-y8y2i4ISpfwEMhLjUfXH9e5qA8qJkKA31tuLakvy
      - PYBOSSA_SESSION_SECRET=test-only-y8y2i4ISpfwEMhLjUfXH9e5qA8qJkKA31tuLakvy
      - PYBOSSA_DATABASE_URL=postgresql://dfuser:test-only-RDkWWAG9jXMAFO8pXu6K@pybossa-db/dforce
      - PYBOSSA_ITSDANGEROUS_SECRET=test-only-2R1ucOk8KxEeh5SCaXcWPt4oDf2sHQvpiyHAPoyX
      - PYBOSSA_BRAND=Helpful Engineering
      - PYBOSSA_TITLE=Helpful Engineering
      - PYBOSSA_LOGO=default_logo.svg
    depends_on:
      - pybossa-db
    ports:
      - "8000:80"

  pybossa-db:
    image: postgres
    environment:
      - POSTGRES_USER=dfuser
      - POSTGRES_PASSWORD=test-only-Spoonful78squinted37supra
      - POSTGRES_DB=dforce
